package signalbait.dto.nlp;


public enum SignalCategory {
    URGENT,
    THREATENING,
    CREDENTIAL_REQUEST,
    FINANCIAL_REQUEST,
    PRESSURE_TO_ACT,
    IMPERSONATION,
    ACCOUNT_TAKEOVER,
    MALICIOUS_ATTACHMENT,
    SOCIAL_ENGINEERING,
}
